# Generated by Django 6.0.2 on 2026-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InterviewScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_token", models.CharField(max_length=200, unique=True)),
                ("candidate_name", models.CharField(max_length=100)),
                ("candidate_email", models.EmailField(max_length=254)),
                ("raw_score", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("total_questions", models.IntegerField(default=10)),
                ("evaluated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
