# Generated by Django 6.0.2 on 2026-02-20 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecretInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("candidate_name", models.CharField(max_length=100)),
                ("candidate_email", models.EmailField(max_length=254)),
                ("interviewer_name", models.CharField(max_length=100)),
                ("system_prompt", models.TextField()),
                ("interview_datetime", models.DateTimeField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used", models.BooleanField(default=False)),
            ],
        ),
    ]
