# Generated by Django 6.0.2 on 2026-02-20 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretinterview",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="secretinterview",
            name="system_prompt",
            field=models.TextField(max_length=2000),
        ),
    ]
