# Generated by Django 6.0.2 on 2026-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_interview", "0002_secretinterview_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretinterview",
            name="passcode",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
