# Generated by Django 6.0.2 on 2026-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_interview", "0003_secretinterview_passcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="secretinterview",
            name="coding_difficulty",
            field=models.CharField(blank=True, default="medium", max_length=20),
        ),
        migrations.AddField(
            model_name="secretinterview",
            name="coding_language",
            field=models.CharField(blank=True, default="python", max_length=50),
        ),
        migrations.AddField(
            model_name="secretinterview",
            name="coding_question",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="secretinterview",
            name="coding_topic",
            field=models.CharField(blank=True, default="Arrays", max_length=100),
        ),
    ]
